touch server.js
touch .env
mkdir routes
touch routes/auth.js
touch routes/words.js
mkdir models
touch models/User.js
touch models/Word.js
mkdir config
touch config/db.js
mkdir middleware
touch middleware/authMiddleware.js
